# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f4276b395fa3a24c92b4904652d17d469c619b4bd915109e22da9c2350a7590314ab31f3941435dedb9e7e8d886d54de2e71d3710ee45d3b62ce8c1f973c113

test:
  secret_key_base: bc4577f9154d0925db558084599be25f556f68fe3166fa5d1448eaaf393682a703d36980170b5d0b715932bde550fae5e836ddde3b3d7f475874ecdcb41fe740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
